---
# tasks file for Openvpn

# - name: debug variables
#   debug: msg="{{ hostvars[item]['v_inet'] }} {{ openvpn_ip }} {{ openvpn_port }}"
#   with_items: groups['all']
#   tags:
#     - debug

# Server tasks

- name: install and/or ensure openvpn is the latest version
  apt: pkg=openvpn state=latest update_cache=yes

- name: copy server configuration to /etc/openvpn/
  template:
    src=server.conf.j2
    dest=/etc/openvpn/server.conf
    owner=root

- name: copy vars file
  template:
    src=vars.j2
    dest=/etc/openvpn/vars
    owner=root

- name: create client certs and conf
  script:
    createclient.sh {{ item }} {{ openvpn_ip }} {{ openvpn_port }}
    creates=/etc/openvpn/clientconf/{{ item }}/{{ item }}.conf
  with_items: groups['production']

- name: create client-conf-dir for static ip assignment
  command:
    /bin/mkdir -p /etc/openvpn/ccd/

- name: create ccd for jail
  command:
    /bin/mkdir -p /etc/openvpn/jail/ccd/

- name: create specific static ip file for every nodes
  shell:
    /bin/echo "ifconfig-push {{ virtual_network }}{{ hostvars[item]['v_ptp'] }} 
    {{ virtual_network }}{{ hostvars[item]['v_inet'] }}"
    > /etc/openvpn/ccd/{{ item }}
  with_items: groups['production']

- name: copy ccd content to jail
  command:
    cp -R /etc/openvpn/ccd/ /etc/openvpn/jail/ccd/

- name: Restart OpenVPN
  action: service name=openvpn state=restarted

- name: fetch every files from every nodes to local tmp
  synchronize:
    mode=pull
    delete=yes
    src=/etc/openvpn/clientconf/{{ item }}
    dest=/tmp/
  with_items: groups['production']
