---
# tasks file for shinken

- name: install snmpd
  apt: pkg=snmpd state=latest update_cache=yes

- name: setup snmpd.conf
  template:
    src=snmpd.conf.j2
    dest=/etc/snmp/snmpd.conf

- name: restart snmpd
  action: service name=snmpd state=restarted