---
# tasks file for shinken

- name: install linux-snmp pack
  command:
    shinken install {{ item }}
  with_items:
    - ['linux-snmp', 'http', 'postgresql']

- name: instlal check_postgres nagios plugins
  copy:
    src=check_postgres.pl
    dest=/var/lib/shinken/libexec/

- name: set uid to root for check_postgres
  command:
    chmod u+s /var/lib/shinken/libexec/check_postgres.pl

- name: make it executable
  command:
    chmod +x /var/lib/shinken/libexec/check_postgres.pl

- name: create symbolic link to fix missing utils.pm in perl5
  command:
    ln -s /usr/lib/nagios/plugins/utils.pm /usr/share/perl5/
  args:
    creates: /usr/share/perl5/utils.pm

- name: set uid to root for check_icmp plugins to get generic-host working
  command:
    chmod u+s /usr/lib/nagios/plugins/check_icmp

- name: setup hosts
  template:
    src=hosts.j2
    dest=/etc/shinken/hosts/{{ item }}.cfg
  with_flattened:
    - groups['production']
    - groups['production-websites']

- name: customized linux-snmp pack
  copy:
    src=linux-snmp/
    dest=/etc/shinken/packs/linux-snmp/

- name: restart shinken
  action: service name=shinken state=restarted