---
# tasks file for shinken

- name: install linux-snmp pack
  command:
    shinken install {{ item }}
  with_items:
    - ['linux-snmp', 'http', 'postgresql']

- name: install additional nagios plugins
  copy:
    src={{ item }}
    dest=/var/lib/shinken/libexec/
  with_items:
    - ['check_postgres.pl', 'check_nginx_status.pl']

- name: set uid to root for plugins
  command:
    chmod u+s /var/lib/shinken/libexec/{{ item }}
  with_items:
    - ['check_postgres.pl', 'check_nginx_status.pl']

- name: make them executable
  command:
    chmod +x /var/lib/shinken/libexec/{{ item }}
  with_items:
    - ['check_postgres.pl', 'check_nginx_status.pl']

- name: create symbolic link to fix missing utils.pm in perl5
  command:
    ln -s /usr/lib/nagios/plugins/utils.pm /usr/share/perl5/
  args:
    creates: /usr/share/perl5/utils.pm

- name: set uid to root for check_icmp plugins to get generic-host working
  command:
    chmod u+s /usr/lib/nagios/plugins/check_icmp

- name: setup hosts
  template:
    src=hosts.j2
    dest=/etc/shinken/hosts/{{ item }}.cfg
  with_flattened:
    - groups['production']
    - groups['production-websites']

- name: setup additional hosts (dummy)
  synchronize: src=hosts/ dest=/etc/shinken/hosts/

- name: customized packs (shinken)
  copy:
    src={{ item }}/
    dest=/etc/shinken/packs/{{ item }}/
  with_items:
    - ['linux-snmp', 'nginx']

- name: customized packs (tandoori)
  copy:
    src={{ item }}/ dest=/etc/shinken/packs/{{ item }}
  with_items:
    - pacemaker
    - uwsgi

- name: custom services
  synchronize: src=services/ dest=/etc/shinken/services/

- name: restart shinken
  action: service name=shinken state=restarted