#!/bin/bash

OUTPUT=`/usr/lib/nagios/plugins/check_snmp -H $1 -t30 -C $2 -o .1.3.6.1.4.1.2021.8.1.101.1 -r "APT OK"`
STATE=${PIPESTATUS[0]}
echo ${OUTPUT#SNMP}
# everything !ok is warning only
if [ $STATE == 0 ]; then
    exit 0
else
    exit 1
fi
