---
# Mail servers

- hosts: mailservers
  roles:
    - { role: collectd,
        collectd_plugins:
          [{ plugin: "load" },
           { plugin: "memory" },
           { plugin: "df" }],

        collectd_plugins_multi:
        { interface: { Interface: '"eth0"' },
          network: { Server: '"37.187.75.67" "25826"' } },

        tags: ["collectd"]
      }