---
# Middleware servers

- hosts: middlewares
  roles:
    - { role: tonioo.server_setup,
        tags: ["base"] }
    
    - { role: valentinogagliardi.collectd,
        collectd_plugins:
          [{ plugin: "load" },
           { plugin: "memory" },
           { plugin: "df" }],

        collectd_plugins_multi:
        { interface: { 1: 'Interface "eth0"',
                       2: 'Interface "eth1"' },
          network: { Server: '"37.187.75.67" "25826"' } },

        tags: ["collectd"]
      }

    - { role: geerlingguy.logstash-forwarder,
        logstash_forwarder_logstash_server: 37.187.75.67,
        logstash_forwarder_logstash_server_port: 5000,
        logstash_ssl_dir: /etc/pki/tls/certs,
        logstash_forwarder_ssl_certificate_file: logstash-forwarder.crt,

        logstash_forwarder_files:
        [ { paths: [
              "/var/log/messages",
              "/var/log/auth.log"
            ],
            fields: { type: syslog } }, ],

        tags: ["logstash"]
      }

    - { role: tonioo.postfix,
        tags: ["postfix"] }

  tasks:
    - name: Install monitoring packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - uwsgi-plugin-ping

      tags: monitoring
