---
# OpenVPN playbook

- hosts: production
  sudo: yes
  tasks:
  - name: install and/or ensure openvpn is the latest version
    apt: pkg=openvpn state=latest update_cache=yes
  - name: copy keys and certs to /etc/openvpn/ to auto start tunnel at boot
    copy: src=templates/openvpn/ dest=/etc/openvpn/ owner=root
  - name: ensure that service has been restarted
    service: name=openvpn state=restarted