---
galaxy_info:
  author: Antoine Nguyen
  description: Install and configure Postfix
  company: Spicesoft
  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: Debian
    versions:
      - wheezy

  categories:
  - system
  - mail

dependencies: []
